*** Starting uWSGI 2.0.15 (64bit) on [Tue May 16 23:20:21 2017] ***
compiled with version: 6.3.0 20170221 on 16 May 2017 23:18:30
os: Linux-3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30)
nodename: massimo
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /var/www-python/AlphaPeriodicity
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7972
your memory page size is 4096 bytes
detected max file descriptor number: 65536
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8087 fd 3
Python version: 2.7.13 (default, Jan 19 2017, 14:48:08)  [GCC 6.3.0 20170118]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x7f2c343afdb0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72768 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x7f2c343afdb0 pid: 32720 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 32720, cores: 1)
*** Starting uWSGI 2.0.15 (64bit) on [Tue May 16 23:22:47 2017] ***
compiled with version: 6.3.0 20170221 on 16 May 2017 23:18:30
os: Linux-3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30)
nodename: massimo
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /var/www-python/AlphaPeriodicity
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7972
your memory page size is 4096 bytes
detected max file descriptor number: 65536
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8087 fd 3
Python version: 2.7.13 (default, Jan 19 2017, 14:48:08)  [GCC 6.3.0 20170118]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x7f75d0900db0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72768 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x7f75d0900db0 pid: 354 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 354, cores: 1)
[pid: 354|app: 0|req: 1/1] 127.0.0.1 () {42 vars in 1196 bytes} [Tue May 16 23:22:49 2017] GET /periodicity/ => generated 40 bytes in 0 msecs (HTTP/1.0 200) 1 headers in 44 bytes (1 switches on core 0)
[pid: 354|app: 0|req: 2/2] 127.0.0.1 () {42 vars in 1196 bytes} [Tue May 16 23:22:50 2017] GET /periodicity/ => generated 40 bytes in 0 msecs (HTTP/1.0 200) 1 headers in 44 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.15 (64bit) on [Tue May 16 23:23:46 2017] ***
compiled with version: 6.3.0 20170221 on 16 May 2017 23:18:30
os: Linux-3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30)
nodename: massimo
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /var/www-python/AlphaPeriodicity
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7972
your memory page size is 4096 bytes
detected max file descriptor number: 65536
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8087 fd 3
Python version: 2.7.13 (default, Jan 19 2017, 14:48:08)  [GCC 6.3.0 20170118]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x7f2f887badb0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72768 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x7f2f887badb0 pid: 393 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 393, cores: 1)
[pid: 393|app: 0|req: 1/1] 127.0.0.1 () {42 vars in 1196 bytes} [Tue May 16 23:23:54 2017] GET /periodicity/ => generated 40 bytes in 0 msecs (HTTP/1.0 200) 1 headers in 44 bytes (1 switches on core 0)
[pid: 393|app: 0|req: 2/2] 127.0.0.1 () {42 vars in 1196 bytes} [Tue May 16 23:23:55 2017] GET /periodicity/ => generated 40 bytes in 0 msecs (HTTP/1.0 200) 1 headers in 44 bytes (1 switches on core 0)
[pid: 393|app: 0|req: 3/3] 127.0.0.1 () {42 vars in 1196 bytes} [Tue May 16 23:23:55 2017] GET /periodicity/ => generated 40 bytes in 0 msecs (HTTP/1.0 200) 1 headers in 44 bytes (1 switches on core 0)
[pid: 393|app: 0|req: 4/4] 127.0.0.1 () {42 vars in 1196 bytes} [Tue May 16 23:23:55 2017] GET /periodicity/ => generated 40 bytes in 0 msecs (HTTP/1.0 200) 1 headers in 44 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "PeriodicityCharacterizer.py", line 1, in <module>
    from nltk import ngrams
ImportError: No module named nltk
Traceback (most recent call last):
  File "PeriodicityCharacterizer.py", line 54, in <module>
    cur.execute("select * from idProbeAnchorToPaths where probeId="+idProbe+" and idMeas="+idMeas+";")
  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, u"Unknown column 'PeriodicityCharacterizer.py' in 'where clause'")
{'4300': 'l', '1300': 'q', '700': 'h', '3800': 'e', '2900': 'w', '3000': 'D', '3900': 'v', '3300': 'j', '4800': 'u', '4700': 'i', '4000': 'd', '2300': 'c', '1500': 'A', '2400': 'o', '1400': 's', '500': 'a', '2500': 'f', '200': 'n', '3600': '@', '2700': 'x', '3400': 'p', '100': 'E', '4600': 'g', '1700': 'b', '900': 'y', '2100': 'k', '1800': 'r', '3500': 'm', '4400': 'C', '2000': 'B', '1100': 'z', '800': 't'}
set(['ghijklmnopqkrstu', 'abaacadceffcfaef', 'ghijklmnopqkrstk', 'vwxyz@ABxCyDwzEv'])
